<?php

namespace GingerCoreTest\Util;

use GingerCore\Util\Util;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-10 at 23:48:42.
 */
class UtilTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Ginger\Core\Util\Util::getType
     */
    public function testGetType()
    {
        $this->assertEquals('null', Util::getType(NULL));
        $this->assertEquals('string', Util::getType('a string'));
        $this->assertEquals('stdClass', Util::getType(new \stdClass()));
        $this->assertEquals('GingerCoreTest\Util\UtilTest', Util::getType($this));
    }

}
