language: php

php:
  - 5.4

services:
  - mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer --dev install

script:
  - php ./vendor/bin/phpunit -c ./tests/.

