language: php

php:
  - 5.5

before_script:
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer --dev install

script:
  - php ./vendor/bin/phpunit -c ./tests/.

