<?php

namespace GingerCoreTest\Repository\Adapter;

use GingerCoreTest\TestCase;
use GingerCore\Repository\Resource;
use GingerCore\Repository\Adapter\ZendDbCrudRepositoryAdapter;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-16 at 19:06:14.
 */
class ZendDbCrudRepositoryAdapterTest extends TestCase
{

    /**
     * @var ZendDbCrudRepositoryAdapter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ZendDbCrudRepositoryAdapter($this->initCrudDatabase());
    }

    

    /**
     * @covers GingerCore\Repository\Adapter\ZendDbCrudRepositoryAdapter::createResource
     */
    public function testCreateResource()
    {
        $resourceType = new Resource\ResourceType('workflow');
        $resourceData = new Resource\ResourceData();
        $resourceData->setData(array('name' => 'DataTransfer'));
        
        $resourceId = $this->object->createResource($resourceType, $resourceData);
        
        $this->assertInstanceOf('GingerCore\Repository\Resource\ResourceId', $resourceId);
        $this->assertEquals(1, $resourceId->getValue());
    }

    /**
     * @covers GingerCore\Repository\Adapter\ZendDbCrudRepositoryAdapter::deleteResource
     */
    public function testDeleteResource()
    {
        $resourceType = new Resource\ResourceType('workflow');
        $resourceData = new Resource\ResourceData();
        $resourceData->setData(array('name' => 'DataTransfer'));
        
        $resourceId = $this->object->createResource($resourceType, $resourceData);
        
        $this->object->deleteResource($resourceType, $resourceId);
        
        //If no exception was thrown, deletion of resource was successful
        $this->assertTrue(true);
    }

    /**
     * @covers GingerCore\Repository\Adapter\ZendDbCrudRepositoryAdapter::getResource
     */
    public function testGetResource()
    {
        $resourceType = new Resource\ResourceType('workflow');
        $resourceData = new Resource\ResourceData();
        $resourceData->setData(array('name' => 'DataTransfer'));
        
        $resourceId = $this->object->createResource($resourceType, $resourceData);
        
        $resourceData = $this->object->getResource($resourceType, $resourceId);
        
        $this->assertInstanceOf('GingerCore\Repository\Resource\ResourceData', $resourceData);
        $this->assertEquals($resourceId->getValue(), $resourceData->getResourceId()->getValue());
        $this->assertEquals(array('name' => 'DataTransfer'), $resourceData->getData());        
    }

    /**
     * @covers GingerCore\Repository\Adapter\ZendDbCrudRepositoryAdapter::getResources
     */
    public function testGetResources()
    {
        $resourceType = new Resource\ResourceType('workflow');
        $resourceData = new Resource\ResourceData();
        $resourceData->setData(array('name' => 'DataTransfer'));
        
        $resourceId1 = $this->object->createResource($resourceType, $resourceData);
        
        $resourceData = new Resource\ResourceData();
        $resourceData->setData(array('name' => 'FileUpload'));
        
        $resourceId2 = $this->object->createResource($resourceType, $resourceData);
        
        $resources = $this->object->getResources($resourceType);
        
        $resourceData1 = $resources[0];
        
        $this->assertInstanceOf('GingerCore\Repository\Resource\ResourceData', $resourceData1);
        $this->assertEquals($resourceId1->getValue(), $resourceData1->getResourceId()->getValue());
        $this->assertEquals(array('name' => 'DataTransfer'), $resourceData1->getData());
        
        $resourceData2 = $resources[1];
        
        $this->assertInstanceOf('GingerCore\Repository\Resource\ResourceData', $resourceData2);
        $this->assertEquals($resourceId2->getValue(), $resourceData2->getResourceId()->getValue());
        $this->assertEquals(array('name' => 'FileUpload'), $resourceData2->getData());
    }

    /**
     * @covers GingerCore\Repository\Adapter\ZendDbCrudRepositoryAdapter::updateResource
     */
    public function testUpdateResource()
    {
        $resourceType = new Resource\ResourceType('workflow');
        $resourceData = new Resource\ResourceData();
        $resourceData->setData(array('name' => 'DataTransfer', 'desc' => 'simple data transfer'));
        
        $resourceId = $this->object->createResource($resourceType, $resourceData);
        
        $resourceData = new Resource\ResourceData($resourceId);
        $resourceData->setData(array('name' => 'FileUpload'));
        
        $resourceData = $this->object->updateResource($resourceType, $resourceData);
        
        $this->assertInstanceOf('GingerCore\Repository\Resource\ResourceData', $resourceData);
        $this->assertEquals($resourceId->getValue(), $resourceData->getResourceId()->getValue());
        $this->assertEquals(
            array(
                'name' => 'FileUpload', 
                'desc' => 'simple data transfer'
            ), 
            $resourceData->getData()
        );
    }
}
